# Generated by Django 4.2 on 2024-09-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.BooleanField(default=False, verbose_name='Расписание создано на текущую неделю')),
                ('week_number', models.IntegerField(default=0, verbose_name='Номер недели')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Месяц')),
                ('quantity_conducted', models.IntegerField(default=0, verbose_name='Количество проведенных')),
                ('quantity_paid', models.IntegerField(default=0, verbose_name='Количество оплаченных')),
            ],
            options={
                'verbose_name': 'Учёт занятий',
                'verbose_name_plural': 'Учёты занятий',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('cost', models.IntegerField(default=1000, verbose_name='Стоимость часа')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Не выбрано', max_length=50, verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время начала занятия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='accounting.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'День занятия',
                'verbose_name_plural': 'Дни занятий',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Месяц и год оплаты')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата проведения занятия')),
                ('paid_for', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('conducted', models.BooleanField(default=False, verbose_name='Проведено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
