# Generated by Django 4.2 on 2024-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaccounting',
            name='date',
            field=models.CharField(max_length=51, verbose_name='Месяц'),
        ),
    ]
