# Generated by Django 4.2 on 2024-09-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_lessonaccounting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonaccounting',
            name='date',
        ),
        migrations.AddField(
            model_name='lessonaccounting',
            name='month',
            field=models.CharField(default=True, max_length=50, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonaccounting',
            name='year',
            field=models.CharField(default=True, max_length=50, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
