# Generated by Django 4.2 on 2024-09-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='paid_for',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Понедельник', 'Создан'), ('Вторник', 'Собирается'), ('Среда', 'В пути'), ('Четверг', 'Доставлено'), ('Пятница', 'Получено'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Не выбрано', max_length=50, verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'День занятия',
                'verbose_name_plural': 'Дни занятий',
            },
        ),
    ]
