# Generated by Django 4.2 on 2024-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
