# Generated by Django 4.2 on 2024-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_lesson_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonaccounting',
            name='quantity_cancelled',
            field=models.IntegerField(default=0, verbose_name='Количество отменённых'),
        ),
        migrations.AddField(
            model_name='lessonaccounting',
            name='quantity_moved',
            field=models.IntegerField(default=0, verbose_name='Количество перенесённых'),
        ),
    ]
