# Generated by Django 4.2 on 2024-09-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_alter_lesson_student_alter_payment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
            preserve_default=False,
        ),
    ]
