# Generated by Django 4.2 on 2024-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cost',
            field=models.IntegerField(default=1000, verbose_name='Стоимость часа'),
        ),
    ]
